const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
const connectDB = require("./config/db");
const { swaggerUi, specs } = require("./swagger");
const memeRoutes = require("./routes/memeRoutes");
const bidRoutes = require("./routes/bidRoutes");
const leaderboardRoutes = require("./routes/leaderboardRoutes");
const aiRoutes = require("./routes/aiRoutes");
const { createServer } = require("http");
const { setupSocket } = require("./config/socket");

dotenv.config();
const app = express();
const server = createServer(app);
setupSocket(server);
connectDB();
app.use(cors());
app.use(express.json());
app.use("/api/memes", memeRoutes);
app.use("/api/bids", bidRoutes);
app.use("/api/leaderboard", leaderboardRoutes);
app.use("/api/ai", aiRoutes);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
const PORT = process.env.PORT || 5001;
server.listen(PORT, () => console.log(`Server running on port ${PORT}`));
